export enum ESCPOSConst {
  CMP_ALIGNMENT_LEFT = 0,
  CMP_ALIGNMENT_CENTER = 1,
  CMP_ALIGNMENT_RIGHT = 2,
  CMP_BCS_Code128_Parsed,
  CMP_BCS_UPCA = 101,
  CMP_BCS_UPCE = 102,
  CMP_BCS_EAN8 = 103,
  CMP_BCS_EAN13 = 104,
  CMP_BCS_JAN8 = 105,
  CMP_BCS_JAN13 = 106,
  CMP_BCS_ITF = 107,
  CMP_BCS_Codabar = 108,
  CMP_BCS_Code39 = 109,
  CMP_BCS_Code93 = 110,
  CMP_BCS_Code128 = 111,
  CMP_BCS_GS1DATABAR = 131,
  CMP_BCS_GS1DATABAR_E = 132,
  CMP_BCS_GS1DATABAR_S = 133,
  CMP_BCS_GS1DATABAR_E_S = 134,
  CMP_BCS_GS1DATABAR_T = 135,
  CMP_BCS_GS1DATABAR_L = 136,
  CMP_BCS_GS1DATABAR_S_O = 137,
  CMP_BM_ASIS = -11,
  CMP_BM_MODE_CMD_RASTER = 1,
  CMP_BM_MODE_CMD_BITIMAGE = 2,
  CMP_BM_MODE_CMD_GRAY16DOWNLOAD = 4,
  CMP_BM_MODE_CMD_MONO = 8,
  CMP_BM_MODE_CMD_GRAY16 = 8,
  CMP_BM_MODE_HT_THRESHOLD = 16,
  CMP_BM_MODE_HT_DITHER = 32,
  CMP_CHECKSUM_ERROR,
  CMP_CUT_FULL = -1,
  CMP_CUT_PARTIAL = -2,
  CMP_CUT_FULL_PREFEED = -3,
  CMP_CUT_PARTIAL_PREFEED = -4,
  CMP_DRAWER_1 = 1,
  CMP_DRAWER_2 = 2,
  CMP_E_BT_DISABLE,
  CMP_E_BT_NODEVICE,
  CMP_E_CONNECTED = 1001,
  CMP_E_DISCONNECT = 1002,
  CMP_E_NOTCONNECT = 1003,
  CMP_E_CONNECT_NOTFOUND = 1004,
  CMP_E_CONNECT_OFFLINE = 1005,
  CMP_E_NOCONTEXT = 1006,
  CMP_E_ILLEGAL = 1101,
  CMP_E_OFFLINE = 1102,
  CMP_E_NOEXIST = 1103,
  CMP_E_FAILURE = 1104,
  CMP_E_TIMEOUT = 1105,
  CMP_E_NO_LIST = 1106,
  CMP_EPTR_COVER_OPEN = 1201,
  CMP_EPTR_REC_EMPTY = 1202,
  CMP_EPTR_BADFORMAT = 1203,
  CMP_EPTR_TOOBIG = 1204,
  CMP_FNT_DEFAULT = 0b0,
  CMP_FNT_FONTB = 0b1,
  CMP_FNT_FONTC = 0b10,
  CMP_FNT_BOLD = 0b100,
  CMP_FNT_REVERSE = 0b1000,
  CMP_FNT_UNDERLINE = 0b10000,
  CMP_FNT_ITALIC = 0b100000,
  CMP_FNT_STRIKEOUT = 0b1000000,
  CMP_HRI_TEXT_NONE = 0,
  CMP_HRI_TEXT_ABOVE = 1,
  CMP_HRI_TEXT_BELOW = 2,
  CMP_MF_TO_CUTTER = 2,
  CMP_MF_TO_NEXT_TOF = 8,
  CMP_MM_DOTS = 1,
  CMP_MM_TWIPS = 2,
  CMP_MM_ENGLISH = 3,
  CMP_MM_METRIC = 4,
  CMP_PD_LEFT_TO_RIGHT = 1,
  CMP_PD_BOTTOM_TO_TOP = 2,
  CMP_PD_RIGHT_TO_LEFT = 3,
  CMP_PD_TOP_TO_BOTTOM = 4,
  CMP_PDF417_EC_LEVEL_0 = 48,
  CMP_PDF417_EC_LEVEL_1 = 49,
  CMP_PDF417_EC_LEVEL_2 = 50,
  CMP_PDF417_EC_LEVEL_3 = 51,
  CMP_PDF417_EC_LEVEL_4 = 52,
  CMP_PDF417_EC_LEVEL_5 = 53,
  CMP_PDF417_EC_LEVEL_6 = 54,
  CMP_PDF417_EC_LEVEL_7 = 55,
  CMP_PDF417_EC_LEVEL_8 = 56,
  CMP_PM_BITMAP = 0b1,
  CMP_PM_BARCODE = 0b10,
  CMP_PM_BM_ROTATE = 0b100,
  CMP_PM_BC_ROTATE = 0b1000,
  CMP_PM_OPAQUE = 0b10000,
  CMP_PM_PAGE_MODE = 1,
  CMP_PM_PRINT_SAVE = 2,
  CMP_PM_NORMAL = 3,
  CMP_PM_CANCEL = 4,
  CMP_PORT_Bluetooth = 1,
  CMP_PORT_Bluetooth_Insecure = 2,
  CMP_PORT_WiFi = 0,
  CMP_PORT_USB = 3,
  CMP_PORT_SNMP = 6,
  CMP_QRCODE_EC_LEVEL_L = 48,
  CMP_QRCODE_EC_LEVEL_M = 49,
  CMP_QRCODE_EC_LEVEL_Q = 50,
  CMP_QRCODE_EC_LEVEL_H = 51,
  CMP_RT_NORMAL = 0x0001,
  CMP_RT_ROTATE180 = 0x0103,
  CMP_RP_BARCODE = 0x1000,
  CMP_RP_BITMAP = 0x2000,
  CMP_RP_NORMAL = 1,
  CMP_RP_RIGHT90 = 257,
  CMP_RP_LEFT90 = 258,
  CMP_RP_ROTATE180 = 259,
  CMP_SIDE_RIGHT = 0,
  CMP_SIDE_LEFT = 1,
  CMP_STATUS_ONLINE = 2001,
  CMP_STATUS_OFFLINE = 2002,
  CMP_STS_NORMAL = 0b0,
  CMP_STS_ONPRESENTER = 0b1,
  CMP_STS_PAPER_ONPRESENTER = 0b1,
  CMP_STS_DRAWER_LEVEL_H = 0b10,
  CMP_STS_PAPER_NEAREMPTY = 0b100,
  CMP_STS_BATTERY_LOW = 0b1000,
  CMP_STS_COVER_OPEN = 0b10000,
  CMP_STS_PAPER_EMPTY = 0b100000,
  CMP_STS_MSR_READ = 0b1000000,
  CMP_STS_PRINTEROFF = 0b10000000,
  CMP_SUCCESS = 0,
  CMP_TIMEOUT_ERROR,
  CMP_TP_TRANSACTION = 11,
  CMP_TP_NORMAL = 12,
  CMP_TXT_1WIDTH = 0,
  CMP_TXT_2WIDTH = 16,
  CMP_TXT_3WIDTH = 32,
  CMP_TXT_4WIDTH = 48,
  CMP_TXT_5WIDTH = 64,
  CMP_TXT_6WIDTH = 80,
  CMP_TXT_7WIDTH = 96,
  CMP_TXT_8WIDTH = 112,
  CMP_TXT_1HEIGHT = 0,
  CMP_TXT_2HEIGHT = 1,
  CMP_TXT_3HEIGHT = 2,
  CMP_TXT_4HEIGHT = 3,
  CMP_TXT_5HEIGHT = 4,
  CMP_TXT_6HEIGHT = 5,
  CMP_TXT_7HEIGHT = 6,
  CMP_TXT_8HEIGHT = 7,
  CMP_WM_STOP = 0,
  CMP_WM_START = 1,
}

export type ESCPOSPrinterConnectType =
  | ESCPOSConst.CMP_PORT_Bluetooth
  | ESCPOSConst.CMP_PORT_Bluetooth_Insecure
  | ESCPOSConst.CMP_PORT_WiFi
  | ESCPOSConst.CMP_PORT_USB
  | ESCPOSConst.CMP_PORT_SNMP;

export type ESCPOSPrinterStatus =
  | ESCPOSConst.CMP_STS_PRINTEROFF
  | ESCPOSConst.CMP_STS_MSR_READ
  | ESCPOSConst.CMP_STS_PAPER_EMPTY
  | ESCPOSConst.CMP_STS_COVER_OPEN
  | ESCPOSConst.CMP_STS_BATTERY_LOW
  | ESCPOSConst.CMP_STS_PAPER_NEAREMPTY
  | ESCPOSConst.CMP_STS_DRAWER_LEVEL_H
  | ESCPOSConst.CMP_STS_ONPRESENTER;

export type ESCPOSPrinterPrintAlignment =
  | ESCPOSConst.CMP_ALIGNMENT_LEFT
  | ESCPOSConst.CMP_ALIGNMENT_CENTER
  | ESCPOSConst.CMP_ALIGNMENT_RIGHT;

export type ESCPOSPrinterTextAttribute =
  | ESCPOSConst.CMP_FNT_DEFAULT
  | ESCPOSConst.CMP_FNT_FONTB
  | ESCPOSConst.CMP_FNT_FONTC
  | ESCPOSConst.CMP_FNT_BOLD
  | ESCPOSConst.CMP_FNT_REVERSE
  | ESCPOSConst.CMP_FNT_UNDERLINE;

export type ESCPOSPrinterTextSize =
  | ESCPOSConst.CMP_TXT_1WIDTH
  | ESCPOSConst.CMP_TXT_2WIDTH
  | ESCPOSConst.CMP_TXT_3WIDTH
  | ESCPOSConst.CMP_TXT_4WIDTH
  | ESCPOSConst.CMP_TXT_5WIDTH
  | ESCPOSConst.CMP_TXT_6WIDTH
  | ESCPOSConst.CMP_TXT_7WIDTH
  | ESCPOSConst.CMP_TXT_8WIDTH
  | ESCPOSConst.CMP_TXT_1HEIGHT
  | ESCPOSConst.CMP_TXT_2HEIGHT
  | ESCPOSConst.CMP_TXT_3HEIGHT
  | ESCPOSConst.CMP_TXT_4HEIGHT
  | ESCPOSConst.CMP_TXT_5HEIGHT
  | ESCPOSConst.CMP_TXT_6HEIGHT
  | ESCPOSConst.CMP_TXT_7HEIGHT
  | ESCPOSConst.CMP_TXT_8HEIGHT;

export type ESCPOSPrinterTypeface =
  | "DEFAULT"
  | "DEFAULT_BOLD"
  | "MONOSPACE"
  | "SERIF"
  | "SANS_SERIF";

export type ESCPOSPrinterFontStyle =
  | ESCPOSConst.CMP_FNT_DEFAULT
  | ESCPOSConst.CMP_FNT_BOLD
  | ESCPOSConst.CMP_FNT_REVERSE
  | ESCPOSConst.CMP_FNT_UNDERLINE
  | ESCPOSConst.CMP_FNT_ITALIC
  | ESCPOSConst.CMP_FNT_STRIKEOUT;

export type ESCPOSPrinterBitmapMode =
  | ESCPOSConst.CMP_BM_MODE_HT_THRESHOLD
  | ESCPOSConst.CMP_BM_MODE_HT_DITHER
  | ESCPOSConst.CMP_BM_MODE_CMD_RASTER
  | ESCPOSConst.CMP_BM_MODE_CMD_BITIMAGE
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16DOWNLOAD;

export type ESCPOSPrinterNVImageMode =
  | ESCPOSConst.CMP_BM_MODE_HT_THRESHOLD
  | ESCPOSConst.CMP_BM_MODE_HT_DITHER
  | ESCPOSConst.CMP_BM_MODE_CMD_MONO
  | ESCPOSConst.CMP_BM_MODE_CMD_GRAY16;

export type ESCPOSPrinterBarcodeType =
  | ESCPOSConst.CMP_BCS_UPCA
  | ESCPOSConst.CMP_BCS_UPCE
  | ESCPOSConst.CMP_BCS_EAN8
  | ESCPOSConst.CMP_BCS_JAN8
  | ESCPOSConst.CMP_BCS_EAN13
  | ESCPOSConst.CMP_BCS_JAN13
  | ESCPOSConst.CMP_BCS_ITF
  | ESCPOSConst.CMP_BCS_Codabar
  | ESCPOSConst.CMP_BCS_Code39
  | ESCPOSConst.CMP_BCS_Code93
  | ESCPOSConst.CMP_BCS_Code128
  | ESCPOSConst.CMP_BCS_GS1DATABAR
  | ESCPOSConst.CMP_BCS_GS1DATABAR_E
  | ESCPOSConst.CMP_BCS_GS1DATABAR_T
  | ESCPOSConst.CMP_BCS_GS1DATABAR_L;

export type ESCPOSPrinterTextPosition =
  | ESCPOSConst.CMP_HRI_TEXT_NONE
  | ESCPOSConst.CMP_HRI_TEXT_ABOVE
  | ESCPOSConst.CMP_HRI_TEXT_BELOW;

export type ESCPOSPrinterPDF417ECLevel =
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_0
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_1
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_2
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_3
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_4
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_5
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_6
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_7
  | ESCPOSConst.CMP_PDF417_EC_LEVEL_8;

export type ESCPOSPrinterQRCodeECLevel =
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_L
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_M
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_Q
  | ESCPOSConst.CMP_QRCODE_EC_LEVEL_H;

export type ESCPOSPrinterGS1DatabarType =
  | ESCPOSConst.CMP_BCS_GS1DATABAR_S
  | ESCPOSConst.CMP_BCS_GS1DATABAR_E_S
  | ESCPOSConst.CMP_BCS_GS1DATABAR_S_O;

export type ESCPOSPrinterCutType =
  | ESCPOSConst.CMP_CUT_FULL
  | ESCPOSConst.CMP_CUT_PARTIAL
  | ESCPOSConst.CMP_CUT_FULL_PREFEED
  | ESCPOSConst.CMP_CUT_PARTIAL_PREFEED;

export type ESCPOSPrinterMarkFeedType =
  | ESCPOSConst.CMP_MF_TO_CUTTER
  | ESCPOSConst.CMP_MF_TO_NEXT_TOF;

export type ESCPOSPrinterDrawer =
  | ESCPOSConst.CMP_DRAWER_1
  | ESCPOSConst.CMP_DRAWER_2;

export type ESCPOSPrinterTransactionControl =
  | ESCPOSConst.CMP_TP_NORMAL
  | ESCPOSConst.CMP_TP_TRANSACTION;

export type ESCPOSPrinterRotation =
  | ESCPOSConst.CMP_RP_ROTATE180
  | ESCPOSConst.CMP_RP_BARCODE
  | ESCPOSConst.CMP_RP_BITMAP
  | ESCPOSConst.CMP_RP_NORMAL;

export type ESCPOSPrinterPageModeControl =
  | ESCPOSConst.CMP_PM_PAGE_MODE
  | ESCPOSConst.CMP_PM_PRINT_SAVE
  | ESCPOSConst.CMP_PM_NORMAL
  | ESCPOSConst.CMP_PM_CANCEL;

export type ESCPOSPrinterWatermarkStart =
  | ESCPOSConst.CMP_WM_START
  | ESCPOSConst.CMP_WM_STOP;

export type ESCPOSPrinterSearchType =
  | ESCPOSConst.CMP_PORT_Bluetooth
  | ESCPOSConst.CMP_PORT_Bluetooth_Insecure
  | ESCPOSConst.CMP_PORT_WiFi;

export type CitizenPrinerInfo =
  | CitizenPrinerBluetoothInfo
  | CitizenPrinerWiFiInfo;

export type CitizenPrinerWiFiInfo = {
  ipAddress: string;
  macAddress: string;
};

export type CitizenPrinerBluetoothInfo = {
  deviceName: string;
  bdAddress: string;
};
